name: Deploy to Lambda
on:
  push:
    branches: [lambda]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
          
    - name: Deploy to Lambda
      run: |
        zip -r deployment.zip index.js package.json node_modules/
        aws lambda update-function-code --function-name naukri-automation --zip-file fileb://deployment.zip
